CLEAN_TWEET = 'clean_tweet'
DATA_FOLDER = 'data/'
LABEL = 'label'
LABEL_NEG = 0
LABEL_POS = 1
TWITTER_FOLDER = 'twitter-datasets/'
TRAIN_NEG = DATA_FOLDER + TWITTER_FOLDER + "train_neg.txt"
TRAIN_POS = DATA_FOLDER + TWITTER_FOLDER + "train_pos.txt"
TRAIN_NEG_FULL = DATA_FOLDER + TWITTER_FOLDER + "train_neg.txt"
TRAIN_POS_FULL = DATA_FOLDER + TWITTER_FOLDER + "train_pos.txt"
TWEET = 'tweet'
